In [1]:
#for absolute path
import os, os.path

rootDir = 'D:\\PIAIC\\SEM 2\\assignment#1\\images'
print(rootDir+"\\")

for _,_,fileList in os.walk(rootDir):
    
    print('Found directory: %s' % fileList)



D:\PIAIC\SEM 2\assignment#1\images\
Found directory: ['img1.jpg', 'img10.jpg', 'img11.jpg', 'img12.jpg', 'img13.jpg', 'img14.jpg', 'img15.jpg', 'img16.jpg', 'img17.jpg', 'img18.jpg', 'img19.jpg', 'img2.jpg', 'img20.jpg', 'img3.jpg', 'img4.jpg', 'img5.jpg', 'img6.jpg', 'img7.jpg', 'img8.jpg', 'img9.jpg']


In [2]:
#from pathfile import path;

# PANDAS

In [72]:
#_analysis_with_panda_series1

In [53]:
import pandas as pd
import numpy as np

In [6]:
obj = pd.Series([1,2,3,4])
obj

0    1
1    2
2    3
3    4
dtype: int64

In [9]:
obj1 = pd.Series([100,200,300,400])
print(obj1.values)
print(obj1.index)


[100 200 300 400]
RangeIndex(start=0, stop=4, step=1)


In [14]:
obj1 = pd.Series([100,200,300,400],index = [1,44,7,0])
print(obj1)
print(obj1.values)
print(obj1.index)


1     100
44    200
7     300
0     400
dtype: int64
[100 200 300 400]
Int64Index([1, 44, 7, 0], dtype='int64')


In [17]:
obj2 = pd.Series([100,200,300,400],index = ['jan','feb','mar','apr'])
print(obj2)
print(obj2.values)
print(obj2.index)


jan    100
feb    200
mar    300
apr    400
dtype: int64
[100 200 300 400]
Index(['jan', 'feb', 'mar', 'apr'], dtype='object')


In [22]:
list1 =['jan','feb','mar','apr']
obj2 = pd.Series([100,200,300,400],list1,name = 'obj22')
print(obj2)


jan    100
feb    200
mar    300
apr    400
Name: obj22, dtype: int64


In [25]:
obj3 = pd.Series([20,30,20,25,30,40,0],['mon','tues','wed','thurs','fri','sat','sun'],name = 'canteen' )
print(obj3)

mon      20
tues     30
wed      20
thurs    25
fri      30
sat      40
sun       0
Name: canteen, dtype: int64


In [33]:
print(obj3['mon'])
print(obj3[0])


20
20


In [48]:
import calendar
list1 = [calendar.month_abbr[i] for i in range(0,13)]
list1

['',
 'Jan',
 'Feb',
 'Mar',
 'Apr',
 'May',
 'Jun',
 'Jul',
 'Aug',
 'Sep',
 'Oct',
 'Nov',
 'Dec']

In [45]:
import random

random.randint(1,101)
randomList = [random.randint(0,100) for i  in range(0,12)]
randomList

[42, 58, 43, 20, 53, 46, 68, 96, 82, 37, 88, 8]

In [57]:
obj4 = pd.Series(randomList,list1[1:],name = 'randomValues')
obj5 = pd.Series(np.random.randint(10,101,size = [12]),list1[1:],name = 'obj5')
print(obj4)
obj5

Jan    42
Feb    58
Mar    43
Apr    20
May    53
Jun    46
Jul    68
Aug    96
Sep    82
Oct    37
Nov    88
Dec     8
Name: randomValues, dtype: int64


Jan     32
Feb    100
Mar     29
Apr     74
May     29
Jun     42
Jul     57
Aug     71
Sep     50
Oct     90
Nov     86
Dec     48
Name: obj5, dtype: int32

In [67]:
print(obj4[['Jan','Dec']]) 
print(obj5[[3,5]]) 
print(obj5[1])

Jan    42
Dec     8
Name: randomValues, dtype: int64
Apr    74
Jun    42
Name: obj5, dtype: int32
100


In [74]:
print('Oct' in obj5)
print('Ocat' in obj5)
48 in obj5

True
False


False

In [86]:
dict1 = { "A" : 1,"B" : 2,"C" : 3,"D" : 4}
obj6 = pd.Series(dict1)
print(obj6)
obj6 = pd.Series(dict1,index=["B","D","A","C"])
print(obj6)

A    1
B    2
C    3
D    4
dtype: int64
B    2
D    4
A    1
C    3
dtype: int64


In [92]:
#throughlist
dict1 = { "A" : 1,"B" : 2,"C" : 3,"D" : 4}
obj6 = pd.Series(list(dict1.values()),list(dict1.keys()))
obj6

A    1
B    2
C    3
D    4
dtype: int64